### ISSUE TITLE
love to add some awsome free youtube videos 

### ISSUE THREAD

**Issue by arpan-pro-learner** [UNO-Coders/Web-Development#105]
topics I can add 
How to start web development 
and other resources 
@Bachittarjeet pls tell me if I can work on it to add more value

**Comment by Bachittarjeet** [comment]
Sure. try to go for beginners friendly Youtube Video Playlist for Different Technologies.

**Comment by arpan-pro-learner** [comment]
@Bachittarjeet I have added the best resources I know for web dev 
also, I would love to add to this and add resources for ml/android/flutter dev

**Comment by Bachittarjeet** [comment]
Yes! I saw. Thank you @Titanpimpale !
